import {raceState, raceControl, recordRaceAnswer, raceRankings} from './race.mjs';
import {normalizeWord, countWords} from './wordcloud.mjs';
export function createEngine(options={},deps){
 const {storageList,trashAsset,persistence,access,path,upload,getJob,serveAsset,validAsset,saveDrawing,dataRoot,cancelJob,converterHealth,http,readFile,randomBytes,randomInt,root,env}=deps;
if(env.PUBLIC_ORIGIN&&env.DEVELOPMENT_LOCAL_CONVERTER==='1')throw Error('公開服務不可使用未隔離轉檔模式');
 const raceNow=options.now||Date.now;
 const store=persistence(options.dataDir||dataRoot),auth=access(options.dataDir||dataRoot,store);
 const rooms=new Map((store.data.rooms||[]).map(([code,r])=>[code,{...r,people:new Map(r.people)}]));
 const owners=store.data.owners||{};
 const persist=()=>store.save({rooms:[...rooms].map(([code,r])=>[code,{...r,people:[...r.people]}]),sessions:[...auth.sessions],owners});
 const owns=(req,asset)=>{const session=auth.session(req);if(session?.teacher)return true;const tokens=[...(session?.members||[]),req.headers.authorization?.replace(/^Bearer /,'')];return [...rooms.values()].some(r=>!r.archived&&tokens.some(t=>r.people.has(t)||r.host===t)&&(r.deck.some(s=>s.asset===asset)||Object.values(r.annotations||{}).includes(asset)||Object.values(r.answers).some(a=>Object.values(a).some(v=>v?.image===asset))));};
 const token=()=>randomBytes(24).toString('hex');
 const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
 const cleanDeck=d=>{if(!Array.isArray(d)||!d.length)throw Error('簡報至少需要一頁');return d.map(s=>{if(!['content','quiz','racequiz','poll','short','board','wordcloud','fill','resource','image','draw'].includes(s.type))throw Error('不支援的活動');if(typeof s.title!=='string'||!s.title.trim()||s.title.length>200)throw Error('請填寫標題（200 字以內）');const o=Array.isArray(s.options)?s.options.map(x=>String(x).slice(0,200)):[];if(['quiz','racequiz','poll'].includes(s.type)&&(o.length<2||o.length>6||o.some(x=>!x.trim())))throw Error('選項需有 2 至 6 個且不可空白');if(['quiz','racequiz'].includes(s.type)&&(!Number.isInteger(s.correct)||s.correct<0||s.correct>=o.length))throw Error('請指定正確答案');if(s.type==='fill'&&(!String(s.solution||'').trim()||String(s.solution).length>200))throw Error('請填寫填空題答案（200 字以內）');if(s.type==='resource'){let u;try{u=new URL(s.url);}catch{throw Error('請填寫完整的資源網址');}if(u.protocol!=='https:')throw Error('資源網址必須使用 https');}if((s.type==='image'||s.type==='draw')&&s.asset&&!validAsset(s.asset))throw Error('教材圖片路徑無效');if(s.type==='image'&&!s.asset)throw Error('請先上傳圖片');if(s.type==='racequiz'&&(!Number.isInteger(Number(s.seconds??20))||Number(s.seconds??20)<5||Number(s.seconds??20)>300))throw Error('作答時間請設為 5 至 300 秒的整數');return {seconds:s.type==='racequiz'?Number(s.seconds??20):undefined,asset:s.asset,objective:String(s.objective||'').slice(0,1000),criteria:String(s.criteria||'').slice(0,1000),explanation:String(s.explanation||'').slice(0,3000),description:String(s.description||'').slice(0,10000),hint:String(s.hint||'').slice(0,1000),challenge:String(s.challenge||'').slice(0,1000),solution:s.type==='fill'?String(s.solution).trim():undefined,url:s.type==='resource'?String(s.url):undefined,type:s.type,title:s.title.trim(),body:String(s.body||'').slice(0,3000),options:o,correct:['quiz','racequiz'].includes(s.type)?s.correct:null};});};
 const prune=setInterval(()=>{for(const [id,s]of auth.sessions)if(s.expires<Date.now())auth.sessions.delete(id);persist();},60000);prune.unref?.();
 const server=http.createServer(async(req,res)=>{try{
 const raceRequestAt=options.receivedAt??raceNow();
 const url=new URL(req.url,'http://localhost');
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','DENY');
 res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' https://www.youtube.com https://s.ytimg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob:; frame-src https://www.youtube-nocookie.com; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'");
 const allowedOrigins=[env.PUBLIC_ORIGIN||'http://'+req.headers.host,...(env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean)];if(req.method==='POST'&&req.headers.origin&&!allowedOrigins.includes(req.headers.origin))return json(res,403,{error:'請從本站送出請求'});
 if(url.pathname==='/api/health')return json(res,200,{ok:true,persistent:true,converter:await converterHealth(),publicOrigin:env.PUBLIC_ORIGIN||null});
 if(url.pathname==='/api/session')return json(res,200,{teacher:!!auth.session(req)?.teacher});
 if(url.pathname.startsWith('/assets/')&&!owns(req,url.pathname))return json(res,403,{error:'沒有圖片存取權限'});
 if(url.pathname.startsWith('/assets/')&&await serveAsset(req,res,url.pathname))return;
 if(url.pathname==='/api/upload'&&req.method==='POST'){if(!auth.session(req)?.teacher)return json(res,401,{error:'請先登入教師帳號'});if(!auth.rate(req,'upload',10))return json(res,429,{error:'上傳頻繁，請稍後再試'});const job=await upload(req,url.searchParams.get('name')||'');owners[job.id]='teacher';persist();return json(res,202,job);}
 if(url.pathname==='/api/import-status'&&req.method==='GET'){if(!auth.session(req)?.teacher)return json(res,401,{error:'請先登入教師帳號'});const j=await getJob(url.searchParams.get('id'));return json(res,j?200:404,j||{error:'找不到匯入工作'});}
 if(!url.pathname.startsWith('/api/')){if(req.method!=='GET'){res.writeHead(405);return res.end();}const path=url.pathname==='/'?'index.html':url.pathname.slice(1);if(!/^vendor\/[a-zA-Z0-9_./-]+$/.test(path)&&!['index.html','app.js','style.css','landscape.svg','drawing.js','importer.js','example.pdf','enhancements.js','race-ui.js'].includes(path)){res.writeHead(404);return res.end('找不到頁面');}const file=await readFile(root+path);res.writeHead(200,{'Content-Type':{'html':'text/html; charset=utf-8','js':'text/javascript; charset=utf-8','css':'text/css; charset=utf-8','svg':'image/svg+xml','pdf':'application/pdf','mjs':'text/javascript; charset=utf-8','wasm':'application/wasm'}[path.split('.').pop()],'X-Content-Type-Options':'nosniff'});return res.end(file);}
 let b={};if(req.method==='POST'){let raw='',bytes=0;for await(const chunk of req){bytes+=chunk.length;raw+=chunk;if(bytes>(Number(env.MAX_JSON_BYTES)||64*1024*1024))return json(res,413,{error:'資料過大'});}try{b=JSON.parse(raw);}catch{return json(res,400,{error:'資料格式錯誤'});}}
 const p=url.pathname;if(p==='/api/import-cancel'&&req.method==='POST'){if(!auth.session(req)?.teacher)return json(res,401,{error:'請先登入教師帳號'});return json(res,200,{ok:cancelJob(b.id)});}
 if(p==='/api/login'&&req.method==='POST'){if(!auth.rate(req,'login',5))return json(res,429,{error:'嘗試次數過多，請稍後再試'});if(!auth.login(req,res,b.password))return json(res,401,{error:'密碼不正確'});persist();return json(res,200,{ok:true});}
 if(p==='/api/logout'&&req.method==='POST'){const wasTeacher=auth.session(req)?.teacher;auth.logout(req,res);if(wasTeacher)for(const r of rooms.values())r.host=token();persist();return json(res,200,{ok:true});}
 if(p==='/api/rooms'&&req.method==='GET'){if(!auth.session(req)?.teacher)return json(res,401,{error:'請先登入教師帳號'});return json(res,200,{rooms:[...rooms].map(([code,r])=>({code,token:r.host,title:r.deck[0].title,ended:r.ended,updated:r.updated}))});}
 if(p==='/api/storage'&&req.method==='GET'){if(!auth.session(req)?.teacher)return json(res,401,{error:'請先登入教師帳號'});return json(res,200,{files:await storageList(dataRoot),trash:await storageList(path.join(dataRoot,'trash'))});}if(p==='/api/storage-trash'&&req.method==='POST'){if(!auth.session(req)?.teacher)return json(res,401,{error:'請先登入教師帳號'});if(!b.restore&&[...rooms.values()].some(r=>r.deck.some(s=>s.asset?.includes('/'+b.id+'/'))||Object.values(r.answers).some(a=>Object.values(a).some(v=>v?.image?.includes('/'+b.id+'/')))||Object.values(r.annotations||{}).some(a=>a.includes('/'+b.id+'/'))))return json(res,409,{error:'此圖片仍被課堂使用，請保留'});await trashAsset(dataRoot,b.id,!!b.restore);return json(res,200,{ok:true});}if(p==='/api/create'&&!auth.session(req)?.teacher)return json(res,401,{error:'請先登入教師帳號'});
 if(['create','join'].some(x=>p==='/api/'+x)&&!auth.rate(req,p,p.endsWith('join')?Number(env.JOIN_RATE_LIMIT)||300:Number(env.CREATE_RATE_LIMIT)||20))return json(res,429,{error:'請求頻繁，請稍後再試'});
 if(p==='/api/create'&&req.method==='POST'){let code;do{code=String(randomInt(100000,1000000));}while(rooms.has(code));const host=token(),deck=cleanDeck(b.deck);if(deck.some(s=>s.type==='racequiz')&&(deck.length!==10||deck.some(s=>s.type!=='racequiz')))throw Error('競速測驗須包含十題競速選擇題，請使用建立十題競速測驗');rooms.set(code,{...(deck[0].type==='racequiz'?{race:{rounds:{},results:{}}}:{}),host,deck,index:0,reveal:false,ended:false,people:new Map(),answers:{},updated:Date.now()});auth.setSession(req,res,false,host);persist();return json(res,200,{code,token:host});}
 const code=url.searchParams.get('code')||b.code,r=rooms.get(code);if(!r||r.archived)return json(res,404,{error:'找不到教室，請確認六位數代碼'});
 const t=req.headers.authorization?.replace(/^Bearer /,''),host=t===r.host;
 if(p==='/api/join'&&req.method==='POST'){if(r.ended||r.locked)return json(res,409,{error:'這堂課已結束或暫停加入'});const name=String(b.name||'').trim().slice(0,24);if(!name)return json(res,400,{error:'請輸入暱稱'});const id=token();r.people.set(id,name);r.updated=Date.now();auth.setSession(req,res,false,id);persist();return json(res,200,{token:id});}
 if(!host&&!r.people.has(t))return json(res,401,{error:'請重新加入教室'});
 if(p==='/api/strokes'&&req.method==='GET'){const item=host?{image:r.annotations?.[r.index]}:r.answers[r.index]?.[t];let strokes=item?.strokes||null;if(!strokes&&item?.image&&validAsset(item.image)){try{strokes=JSON.parse(await readFile(path.join(dataRoot,item.image.split('/')[2],'strokes.json'),'utf8'));}catch{}}return json(res,200,{index:r.index,strokes});}if(p==='/api/state'&&req.method==='GET'){const race=r.race?raceState(r,t,host,raceNow()):null;const revealed=race?race.phase==='closed':r.reveal;const slide={...r.deck[r.index]};if(!host&&!revealed){delete slide.correct;delete slide.solution;delete slide.explanation;}if(race&&!host&&['waiting','countdown'].includes(race.phase)){slide.title='等待老師開始第 '+(r.index+1)+' 題';slide.body='準備好，倒數結束後題目就會出現。';slide.options=[];delete slide.hint;delete slide.challenge;delete slide.description;}const answers=r.answers[r.index]||{};r.seen??={};r.seen[t]=Date.now();return json(res,200,{video:r.video?.[r.index]||null,index:r.index,total:r.deck.length,slide,...(race?{race}:{}),reveal:revealed,ended:r.ended,people:r.people.size,submitted:Object.keys(answers).length,mine:answers[t]??null,...(slide.type==='wordcloud'&&(host||r.reveal)?{wordcloud:countWords(Object.entries(answers).filter(([id])=>r.people.has(id)).map(([,answer])=>answer))}:{}),annotation:r.annotations?.[r.index]||null,...(r.reveal&&slide.type==='board'?{board:Object.entries(answers).map(([id,answer])=>({name:r.people.get(id),answer}))}:{}),feedback:r.feedback?.[r.index]?.[t]||'',...host?{locked:!!r.locked,roster:[...r.people].map(([id,name])=>({id,name,submitted:answers[id]!==undefined,feedback:r.feedback?.[r.index]?.[id]||'',online:Date.now()-(r.seen?.[id]||0)<10000})),outline:r.deck.map((s,i)=>({index:i,title:s.title,type:s.type,asset:s.asset})),answers:Object.entries(answers).map(([id,answer])=>({id,name:r.people.get(id),answer}))}:{} });}
 if(p==='/api/control'&&req.method==='POST'){if(!host)return json(res,403,{error:'只有教師可以操作'});if(r.ended)return json(res,409,{error:'課程已結束'});if(r.race){try{raceControl(r,b,raceNow());}catch(e){return json(res,409,{error:e.message});}}if(b.video){if(b.indexExpected!==r.index||r.deck[r.index].type!=='resource'||!Number.isFinite(b.video.time)||b.video.time<0||b.video.time>86400||typeof b.video.playing!=='boolean')return json(res,400,{error:'影片控制資料不正確'});r.video??={};r.video[r.index]={time:b.video.time,playing:b.video.playing,at:Date.now()};}if(typeof b.locked==='boolean')r.locked=b.locked;if(b.remove&&r.people.has(b.remove)){r.people.delete(b.remove);}if(b.feedback&&r.people.has(b.feedback.id)){r.feedback??={};r.feedback[r.index]??={};r.feedback[r.index][b.feedback.id]=String(b.feedback.text||'').slice(0,1000);}if(b.annotation){if(b.indexExpected!==r.index)return json(res,409,{error:'頁面已切換'});const drawn=await saveDrawing(b.annotation,b.annotationStrokes);if(b.indexExpected!==r.index)return json(res,409,{error:'頁面已切換'});r.annotations??={};r.annotations[r.index]=drawn.image;}if(Number.isInteger(b.index)){r.index=Math.max(0,Math.min(r.deck.length-1,b.index));r.reveal=false;}if(typeof b.reveal==='boolean')r.reveal=b.reveal;if(b.end===true)r.ended=true;r.updated=Date.now();persist();return json(res,200,{ok:true});}
 if(p==='/api/answer'&&req.method==='POST'){if(host)return json(res,403,{error:'請使用學生身分作答'});if(r.ended||r.reveal||b.index!==r.index)return json(res,409,{error:'題目已切換或作答已截止'});const s=r.deck[r.index];if(['content','resource','image'].includes(s.type))return json(res,400,{error:'此頁無需作答'});let answer=b.answer;if(s.type==='draw'){if(answer?.text){const text=String(answer.text).trim();if(!text||text.length>1000)return json(res,400,{error:'請輸入 1 至 1000 字'});answer={text};}else{answer=await saveDrawing(answer?.image||answer,answer?.strokes);}}else if(s.type==='wordcloud'){answer=normalizeWord(answer);}else if(['short','board','fill'].includes(s.type)){if(typeof answer!=='string'||!answer.trim()||answer.length>1000)return json(res,400,{error:'請輸入 1 至 1000 字'});answer=answer.trim();}else if(!Number.isInteger(answer)||answer<0||answer>=s.options.length)return json(res,400,{error:'請選擇有效選項'});if(r.ended||r.reveal||b.index!==r.index)return json(res,409,{error:'頁面已切換或作答已截止'});if(r.race){try{recordRaceAnswer(r,t,answer,raceRequestAt);}catch(e){return json(res,409,{error:e.message});}}r.answers[r.index]??={};r.history??={};r.history[r.index]??={};r.history[r.index][t]??=[];r.history[r.index][t].push({answer,at:Date.now()});r.answers[r.index][t]=answer;r.updated=Date.now();persist();return json(res,200,{ok:true});}
 if(p==='/api/export'&&req.method==='GET'){if(!host)return json(res,403,{error:'只有教師可以匯出'});return json(res,200,{...(r.race?{rankings:raceRankings(r,t)}:{}),rows:r.deck.flatMap((slide,i)=>['content','resource','image'].includes(slide.type)?[]:[...r.people].map(([id,name])=>{const answer=r.answers[i]?.[id];return ({...(r.race?{points:r.race.results[i]?.[id]?.points??0,elapsedMs:r.race.results[i]?.[id]?.elapsedMs??null}:{}),page:Number(i)+1,title:r.deck[i].title,name:r.people.get(id),submitted:answer!==undefined,feedback:r.feedback?.[i]?.[id]||'',attempts:r.history?.[i]?.[id]?.length||0,answer:typeof answer==='number'?r.deck[i].options[answer]:answer?.text||answer?.image||answer||'',correct:answer===undefined?null:['quiz','racequiz'].includes(r.deck[i].type)?answer===r.deck[i].correct:r.deck[i].type==='fill'?answer===r.deck[i].solution:null});}))});}
 return json(res,404,{error:'找不到此操作'});
 }catch(e){json(res,400,{error:e.message||'操作失敗'});}});
 server.on('close',()=>clearInterval(prune));return server;
}