import {mkdir,readFile,writeFile,readdir,stat} from 'node:fs/promises';
import {createWriteStream,createReadStream} from 'node:fs';
import {Transform} from 'node:stream';
import {pipeline} from 'node:stream/promises';
import {randomUUID} from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {fileURLToPath,pathToFileURL} from 'node:url';
import path from 'node:path';
const exec=promisify(execFile);
export const dataRoot=process.env.DATA_DIR||fileURLToPath(new URL('./data/',import.meta.url));
const jobs=new Map();let queue=Promise.resolve();
const types={'.pdf':'pdf','.ppt':'ppt','.pptx':'pptx','.png':'png','.jpg':'jpg','.jpeg':'jpg','.webp':'webp','.gif':'gif'};
const imageValid=(b,ext)=>ext==='png'?b.subarray(0,8).equals(Buffer.from('89504e470d0a1a0a','hex')):ext==='jpg'?b[0]===255&&b[1]===216&&b[2]===255:ext==='gif'?b.subarray(0,6).toString().match(/^GIF8[79]a$/):ext==='webp'?b.subarray(0,4).toString()==='RIFF'&&b.subarray(8,12).toString()==='WEBP':false;
export const validAsset=url=>typeof url==='string'&&/^\/assets\/[0-9a-f-]{36}\/[a-zA-Z0-9-]+\.(png|jpg|gif|webp)$/.test(url);
export async function upload(req,name){const ext=types[path.extname(name).toLowerCase()];if(!ext)throw Error('支援 PDF、PPT、PPTX、PNG、JPG、WebP 與 GIF');const id=randomUUID(),dir=path.join(dataRoot,id);await mkdir(dir,{recursive:true});const input=path.join(dir,'source.'+ext);let bytes=0;const max=Number(process.env.MAX_UPLOAD_BYTES)||200*1024*1024;await pipeline(req,new Transform({transform(c,e,cb){bytes+=c.length;cb(bytes>max?Error('檔案超過本機上傳容量（預設 200 MB）'):null,c);}}),createWriteStream(input));const job={id,status:'queued',message:'等待轉換',name,created:Date.now()};jobs.set(id,job);queue=queue.catch(()=>{}).then(async()=>{try{job.status='processing';job.message='正在轉換頁面';let images=[];if(['png','jpg','gif','webp'].includes(ext)){const b=await readFile(input);if(!imageValid(b,ext))throw Error('圖片格式不符或檔案已損壞');images=['source.'+ext];}else{let pdf=input;if(ext!=='pdf'){const profile=path.join(dir,'profile');await mkdir(profile,{recursive:true});await writeFile(path.join(profile,'registrymodifications.xcu'),'<?xml version="1.0"?><oor:items xmlns:oor="http://openoffice.org/2001/registry"><item oor:path="/org.openoffice.Office.Common/Security/Scripting"><prop oor:name="MacroSecurityLevel" oor:op="fuse"><value>3</value></prop></item></oor:items>');let fontEnv={};if(process.platform==='darwin'){const fontFile=path.join(dataRoot,'fontconfig.conf');await writeFile(fontFile,'<?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd"><fontconfig><dir>/System/Library/Fonts</dir><dir>/System/Library/Fonts/Supplemental</dir><dir>/Library/Fonts</dir><cachedir>'+path.join(dataRoot,'font-cache')+'</cachedir></fontconfig>');fontEnv.FONTCONFIG_FILE=process.env.FONTCONFIG_FILE||fontFile;}const soffice=process.env.SOFFICE_PATH||fileURLToPath(new URL('./.tools/LibreOffice.app/Contents/MacOS/soffice',import.meta.url));try{await exec(soffice,['-env:UserInstallation='+pathToFileURL(profile).href,'--headless','--convert-to','pdf','--outdir',dir,input],{timeout:180000,maxBuffer:1024*1024,env:{...process.env,...fontEnv}});}catch(e){throw Error(e.code==='ENOENT'?'PowerPoint 轉換引擎未安裝，請先設定 SOFFICE_PATH':'PowerPoint 無法轉換，請檢查是否有密碼或檔案損壞');}pdf=path.join(dir,'source.pdf');}
const {stdout}=await exec('pdfinfo',[pdf],{timeout:30000});const count=Number(stdout.match(/Pages:\s+(\d+)/)?.[1]);if(!count)throw Error('無法讀取 PDF 頁數');for(let i=1;i<=count;i++){job.message='轉換第 '+i+' / '+count+' 頁';job.progress=i-1;job.total=count;const base='page-'+String(i).padStart(6,'0');await exec('pdftoppm',['-f',String(i),'-l',String(i),'-singlefile','-scale-to','1800','-png',pdf,path.join(dir,base)],{timeout:90000,maxBuffer:1024*1024});images.push(base+'.png');}}
job.slides=images.map((file,i)=>({type:'image',title:name.slice(0,160)+' · 第 '+(i+1)+' 頁',body:'',options:[],asset:'/assets/'+id+'/'+file}));job.status='done';job.message='已匯入 '+images.length+' 頁';await writeFile(path.join(dir,'manifest.json'),JSON.stringify(job));}catch(e){job.status='error';job.message=e.message.includes('Command failed')?'PDF 無法轉換，請確認未加密且檔案完整':e.message;}});return {id,status:'queued'};}
export function getJob(id){return jobs.get(id);}
export async function serveAsset(req,res,pathname){if(!validAsset(pathname))return false;try{const file=path.join(dataRoot,pathname.slice('/assets/'.length));const s=await stat(file);res.writeHead(200,{'Content-Type':{'png':'image/png','jpg':'image/jpeg','webp':'image/webp','gif':'image/gif'}[file.split('.').pop()],'Content-Length':s.size,'X-Content-Type-Options':'nosniff','Cache-Control':'private, max-age=3600'});createReadStream(file).pipe(res);return true;}catch{res.writeHead(404);res.end('圖片不存在');return true;}}
export async function saveDrawing(answer){if(typeof answer!=='string'||!answer.startsWith('data:image/png;base64,')||answer.length>8*1024*1024)throw Error('手寫圖片格式錯誤或過大');const b=Buffer.from(answer.slice(22),'base64');if(!imageValid(b,'png'))throw Error('手寫圖片格式錯誤');const id=randomUUID();await mkdir(path.join(dataRoot,id),{recursive:true});await writeFile(path.join(dataRoot,id,'drawing.png'),b);return {image:'/assets/'+id+'/drawing.png'};}
