import {readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const cf='https://moyun-classroom.hk6429.workers.dev',nf='https://moyun-classroom.netlify.app';
const secret=JSON.parse(await readFile(process.argv[2],'utf8'));
const call=async(base,path,body,cookie='',token='')=>{const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{Cookie:cookie,Origin:base,Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,cookie:r.headers.get('set-cookie')?.split(';')[0],data:await r.json()};};
const a=await call(cf,'/api/login',{password:secret.TEACHER_PASSWORD});assert.equal(a.status,200);
const b=await call(nf,'/api/login',{password:secret.TEACHER_PASSWORD});assert.equal(b.status,200);
console.log('雙站登入通過');
const png=await readFile(new URL('../fixtures/lesson.png',import.meta.url));
const upload=await fetch(nf+'/api/upload?name=正式驗證.png',{method:'POST',headers:{Cookie:b.cookie,Origin:nf},body:png});assert.equal(upload.status,202);const job=await upload.json();
const imported=await call(cf,'/api/import-status?id='+job.id,undefined,a.cookie);assert.equal(imported.data.status,'done');
console.log('圖片匯入與跨站讀回通過');
const created=await call(cf,'/api/create',{deck:[{type:'short',title:'雙站驗證：寫下今天的發現'},{type:'draw',title:'手寫互動驗證'},imported.data.slides[0]]},a.cookie);assert.equal(created.status,200);
const {code,token:host}=created.data;
const joined=await Promise.all(Array.from({length:5},(_,i)=>call(nf,'/api/join',{code,name:'驗證學生'+(i+1)})));
for(const j of joined)assert.equal(j.status,200,JSON.stringify(j.data));
console.log('並行加入通過');
const student=joined[0],st=student.data.token;
assert.equal((await call(nf,'/api/answer',{code,index:0,answer:'兩個網址共用同一間教室'},student.cookie,st)).status,200);
const before=await call(cf,'/api/state?code='+code,undefined,a.cookie,host);assert.equal(before.data.people,5);assert.equal(before.data.submitted,1);
await call(cf,'/api/control',{code,index:1},a.cookie,host);
const strokes=[{tool:'brush',size:6,color:'#254e43',points:[{x:10,y:20,p:.5},{x:30,y:40,p:.6}]}];
assert.equal((await call(nf,'/api/answer',{code,index:1,answer:{image:'data:image/png;base64,'+png.toString('base64'),strokes}},student.cookie,st)).status,200);
assert.deepEqual((await call(nf,'/api/strokes?code='+code,undefined,student.cookie,st)).data.strokes,strokes);
assert.equal((await call(nf,'/api/control',{code,index:2},student.cookie,st)).status,403);
const asset=imported.data.slides[0].asset;
assert.equal((await fetch(cf+asset)).status,403);
const image=await fetch(nf+asset,{headers:{Cookie:student.cookie}});assert.equal(image.status,200);assert.deepEqual(Buffer.from(await image.arrayBuffer()),png);
const report=await call(cf,'/api/export?code='+code,undefined,a.cookie,host);assert.equal(report.data.rows.length,10);
const saved=await call(nf,'/api/rooms',undefined,b.cookie);assert.ok(saved.data.rooms.some(r=>r.code===code));
const evidence={at:new Date().toISOString(),cloudflare:cf,netlify:nf,code,checks:['雙站教師登入','Netlify 圖片上傳與 Cloudflare 讀回','5 人並行跨站加入','文字作答同步','手寫 PNG 與筆畫讀回','學生不能控制課堂','未授權圖片拒絕','學生可讀課堂圖片','完整報告含未作答學生','重新請求可恢復課堂'],passed:true};
await writeFile(new URL('../deploy/live-evidence.json',import.meta.url),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify(evidence));
